name: 'dbt_fraud_detection'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
analysis-paths: ["analyses"]
docs-paths: ["docs"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  dbt_fraud_detection:
    materialized: table
